import { Libre_Franklin } from "next/font/google";
import "./globals.css";
import Header from "./(components)/header/Header";
import MenuProvider from "@/context/MenuContext";

const libre = Libre_Franklin({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "700", "900"]
})

export const metadata = {
  title: "3mory - Elegant Fashion",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${libre.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <MenuProvider>
          {children}
          <Header />
        </MenuProvider>

      </body>
    </html>
  );
}
