import { Libre_Franklin } from "next/font/google";
import "./globals.css";
import Header from "./(components)/layout/header/Header";
import MenuProvider from "@/context/MenuContext";
import Cart from "./(components)/features/cart/Cart";
import { ClerkProvider } from "@clerk/nextjs";

import FixedArrow from "./(components)/shared/fixed-arrow/FixedArrow";
import Footer from "./(components)/layout/footer/Footer";
import SubHeader from "./(components)/layout/sub-header/SubHeader";
import { ReduxProvider } from "@/RTK/store/Provider";

const libre = Libre_Franklin({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "700", "900"]
})

export const metadata = {
  title: "3mory - Elegant Fashion",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <ReduxProvider>
        <html lang="en" className={`${libre.className} h-full antialiased`}>
          <body className="min-h-full flex flex-col">
            <MenuProvider>

              <FixedArrow />
              <Cart />
              <SubHeader />
              <Header />
              <main className="flex-1">

                {children}


              </main>
              <Footer />

            </MenuProvider>
          </body>
        </html>
      </ReduxProvider>

    </ClerkProvider>
  );
}
